const os = require('node:os')
console.log('Info del sistema operativo: ')
console.log('=============================')

console.log('Nombre del sistema operativo: ', os.platform())
console.log('Version del sistema operativo: ', os.release())
console.log('Arquitectura del sistema operativo', os.arch())
console.log('CPUs ', os.cpus())
console.log('Memoria total', os.totalmem() / 1024 / 1024, 'MB')
console.log('Memoria libre', os.freemem() / 1024 / 1024, '  MB')
console.log('uptime', os.uptime())
